/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrozoologico;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bent0vict0r
 */
public class Cadastro extends javax.swing.JFrame {
   
    Listagem list = new Listagem();     // Declaração da Classe que contém as Listas
   
    //  Tabela para Animais
    public void LoadTableAnimais(){
        //  Estrutura da Tabela (linhas e colunas)
        DefaultTableModel animais = new DefaultTableModel(new Object[] {"Raça", "Peso", "Jaula", "Restrição"}, 0);
        for(int i = 0; i < list.numeroDeAnimais(); ++i){
            animais.addRow(new Object[] {list.ListAnimal.get(i).getRaca(), list.ListAnimal.get(i).getPeso(), list.ListAnimal.get(i).getJaula(), list.ListAnimal.get(i).getRestricao()});
        }
        tbl_animais.setModel(animais);
    }
    // Tabela para Animais Extintos
    public void LoadTableAnimaisExt(){
        //  Estrutura da Tabela (linhas e colunas)
        DefaultTableModel animaisext = new DefaultTableModel(new Object[] {"Raça", "Peso", "Jaula", "Restrição", "Restantes", "Estimativa"}, 0);
        for(int i = 0; i < list.numeroDeAnimaisExt(); ++i){
            animaisext.addRow(new Object[] {list.ListAnimalExt.get(i).getRaca(), list.ListAnimalExt.get(i).getPeso(), list.ListAnimalExt.get(i).getJaula(), list.ListAnimalExt.get(i).getRestricao(), list.ListAnimalExt.get(i).getEspeciesRestantes(), list.ListAnimalExt.get(i).getEstimativaExtincao()});
        }
        tbl_animaisext.setModel(animaisext);
    }
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);    // Centraliza Tela
        
        /* Inicializa Campos de Textos e Botões como desabilitados
           Até que o botão NOVO seja clicado        */
        c_raca.setEditable(false);
        c_peso.setEditable(false);
        c_jaula.setEditable(false);
        c_especiesrestantes.setEditable(false);
        c_estimativaextincao.setEditable(false);
        c_buscar.setEditable(false);
        c_buscar2.setEditable(false);
        
        btn_apagar.setEnabled(false);
        btn_apagar2.setEnabled(false);
        btn_restricao_sim.setEnabled(false);
        btn_restricao_nao.setEnabled(false);
        btn_riscoextincao_nao.setEnabled(false);
        btn_riscoextincao_sim.setEnabled(false);
        btn_cadastrar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        btn_buscar.setEnabled(false);
        btn_buscar2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c_raca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_peso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_jaula = new javax.swing.JTextField();
        btn_restricao_sim = new javax.swing.JRadioButton();
        btn_restricao_nao = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btn_riscoextincao_sim = new javax.swing.JRadioButton();
        btn_riscoextincao_nao = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_especiesrestantes = new javax.swing.JTextField();
        c_estimativaextincao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_novo = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_animais = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        c_buscar2 = new javax.swing.JTextField();
        btn_buscar2 = new javax.swing.JButton();
        btn_apagar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_animaisext = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        c_buscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_apagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zoológico");

        jLabel1.setText("Raça:");

        jLabel2.setText("Peso:");

        jLabel3.setText("Jaula:");

        jLabel4.setText("Restrição:");

        buttonGroup1.add(btn_restricao_sim);
        btn_restricao_sim.setText("Sim");

        buttonGroup1.add(btn_restricao_nao);
        btn_restricao_nao.setText("Não");

        jLabel5.setText("Extinção:");

        buttonGroup2.add(btn_riscoextincao_sim);
        btn_riscoextincao_sim.setText("Sim");
        btn_riscoextincao_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riscoextincao_simActionPerformed(evt);
            }
        });

        buttonGroup2.add(btn_riscoextincao_nao);
        btn_riscoextincao_nao.setText("Não");
        btn_riscoextincao_nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_riscoextincao_naoActionPerformed(evt);
            }
        });

        jLabel6.setText("Espécies Restantes:");

        jLabel7.setText("Estimativa para Extinção:");

        jLabel8.setText("Meses");

        btn_novo.setText("NOVO");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("CADASTRAR");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel11.setText("Kg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_restricao_sim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_restricao_nao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(btn_riscoextincao_sim)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_riscoextincao_nao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_especiesrestantes, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(c_raca)
                                    .addComponent(c_peso)
                                    .addComponent(c_jaula, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_estimativaextincao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btn_novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cadastrar)))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(c_raca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_jaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_restricao_nao)
                    .addComponent(btn_restricao_sim)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_riscoextincao_nao)
                    .addComponent(btn_riscoextincao_sim)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_especiesrestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c_estimativaextincao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_novo))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        tbl_animais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Raça", "Peso", "Jaula", "Restrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Short.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_animais);

        jLabel10.setText("Jaula:");

        btn_buscar2.setText("BUSCAR");
        btn_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar2ActionPerformed(evt);
            }
        });

        btn_apagar2.setText("APAGAR");
        btn_apagar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar2)
                .addGap(18, 18, 18)
                .addComponent(btn_apagar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(c_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar2)
                    .addComponent(btn_apagar2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Animais", jPanel2);

        tbl_animaisext.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Raça", "Peso", "Jaula", "Restrição", "Restantes", "Estimativa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_animaisext);
        if (tbl_animaisext.getColumnModel().getColumnCount() > 0) {
            tbl_animaisext.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbl_animaisext.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Jaula:");

        btn_apagar.setText("APAGAR");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addGap(18, 18, 18)
                .addComponent(btn_apagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_apagar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Animais Extintos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/******************** BUSCAR ****************************/
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        boolean achou = false;      //  Flag para quando acha na Lista
        short achouTabela;          //  Flag para receber o campo da BUSCA
        
        achouTabela = Short.parseShort(c_buscar.getText());     //  Flag recebe o campo da busca 
        
        //  Percorre Lista do AnimalExtinto
        for(AnimalExtinto aEx: list.ListAnimalExt){
            // SE o campo de BUSCA for igual a jaula do Animal contido na lista
            if (aEx.getJaula() == Short.parseShort(c_buscar.getText())){   
               achou = true;        // Achou o Animal na Lista
               achouTabela = Short.parseShort(c_buscar.getText());      // Flag recebe o campo de BUSCA
            }
        }
        if(achou){         //   Encontrou elemento na lista, procura ele na tabela 
            for(int i = 0; i < tbl_animaisext.getRowCount(); ++i){      // Varredura da tabela
                if(achouTabela == (short)tbl_animaisext.getValueAt(i, 2)){      // Compara falor retirado da Lista
                                                                                // com linhas da coluna 2 (jaula)
                    tbl_animaisext.setRowSelectionInterval(i,i);        // Seleciona linha
                    break;
                }
            }
        }
        
//      Exceção para Animal não encontrado na Lista
        try{
            if(achou == false){
              throw new AnimalNaoEncontrado("Não encontrado");
            }

            }catch(AnimalNaoEncontrado e){
            Component ERRO = null;
            JOptionPane.showMessageDialog(ERRO, "Jaula Vazia.");              
         }      
        
// Exceção para lista de animais vazia
        try{
            if(list.numeroDeAnimaisExt() == 0){
                throw new BaseDeDadosVazia("avisar");
            }
        }catch(BaseDeDadosVazia e){
            Component ERRO = null;
            JOptionPane.showMessageDialog(ERRO, "Base de dados do Zoologico está vazio.");              
        }
     
    

    }//GEN-LAST:event_btn_buscarActionPerformed


/******************** APAGAR (ANIMAL EXTINTO) ****************************/
    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        int index = tbl_animaisext.getSelectedRow();        //  index recebe linha da tabela
        if(index >= 0 && index<list.numeroDeAnimaisExt()){      // Se index estiver entre inicio da tabela e o fim
            list.ListAnimalExt.remove(index);       // Remove da lista
        }
        LoadTableAnimaisExt();      // Carrega na Tabela
    }//GEN-LAST:event_btn_apagarActionPerformed
/******************** APAGAR (ANIMAL) ****************************/
    private void btn_apagar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagar2ActionPerformed
        int index = tbl_animais.getSelectedRow();        //  index recebe linha da tabela
        if(index >= 0 && index<list.numeroDeAnimais()){      // Se index estiver entre inicio da tabela e o fim
            list.ListAnimal.remove(index);       // Remove da lista
        }
        LoadTableAnimais();      // Carrega na Tabela
    }//GEN-LAST:event_btn_apagar2ActionPerformed

    private void btn_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar2ActionPerformed
        
        boolean achou = false;      //  Flag para quando acha na Lista
        short achouTabela;          //  Flag para receber o campo da BUSCA
        
        achouTabela = Short.parseShort(c_buscar2.getText());     //  Flag recebe o campo da busca 
        
        //  Percorre Lista do AnimalExtinto
        for(Animal a: list.ListAnimal){
            // SE o campo de BUSCA for igual a jaula do Animal contido na lista
            if (a.getJaula() == Short.parseShort(c_buscar2.getText())){
               achou = true;        // Achou o Animal na Lista
               achouTabela = Short.parseShort(c_buscar2.getText());      // Flag recebe o campo de BUSCA
            }
        }
        if(achou){         //   Encontrou elemento na lista, procura ele na tabela 
            for(int i = 0; i < tbl_animais.getRowCount(); ++i){      // Varredura da tabela
                if(achouTabela == (short)tbl_animais.getValueAt(i, 2)){         // Compara falor retirado da Lista
                                                                                // com linhas da coluna 2 (jaula)
                    tbl_animais.setRowSelectionInterval(i,i);       // Seleciona linha
                    break;
                }
            }
        }
//      Exceção para Animal não encontrado na Lista
        try{
            if(achou == false){
              throw new AnimalNaoEncontrado("Não encontrado");
            }

            }catch(AnimalNaoEncontrado e){
            Component ERRO = null;
            JOptionPane.showMessageDialog(ERRO, "Jaula Vazia.");              
         }      
        
// Exceção para lista de animais vazia
        try{
            if(list.numeroDeAnimais() == 0){
                throw new BaseDeDadosVazia("avisar");
            }
        }catch(BaseDeDadosVazia e){
            Component ERRO = null;
            JOptionPane.showMessageDialog(ERRO, "Base de dados do Zoologico está vazio.");              
        }     
    

    }//GEN-LAST:event_btn_buscar2ActionPerformed

/******************** CANCELAR ****************************/
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

        //  Limpa campos de Texto
        c_raca.setText("");
        c_estimativaextincao.setText("");
        c_buscar.setText("");
        c_buscar2.setText("");
        c_especiesrestantes.setText("");
        c_jaula.setText("");
        c_peso.setText("");
        //  Seta botões e campos de textos para não serem acessados até que NOVO seja clicado
        c_raca.setEditable(false);
        c_peso.setEditable(false);
        c_jaula.setEditable(false);
        c_especiesrestantes.setEditable(false);
        c_estimativaextincao.setEditable(false);

        btn_novo.setEnabled(true);
        btn_restricao_nao.setEnabled(false);
        btn_restricao_sim.setEnabled(false);
        btn_riscoextincao_nao.setEnabled(false);
        btn_riscoextincao_sim.setEnabled(false);
        btn_cadastrar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        //  Limpa Seleções dos botões
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btn_cancelarActionPerformed

/******************** CADASTRAR ****************************/
    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        int flagCadastro = 0;               // FLAG para controlar preenchimento dos campos

        // Exceção para Campos inválidos
        if(btn_riscoextincao_sim.isSelected()){
            try{
                if(c_raca.getText().trim().equals("") || c_peso.getText().trim().equals("") || c_jaula.getText().trim().equals("") || c_especiesrestantes.getText().trim().equals("") || c_estimativaextincao.getText().trim().equals("")){
                    flagCadastro = 1;       // Campos não foram corretamente preenchidos
                    throw new CamposInvalidos("avisar");
                }
            }catch(CamposInvalidos e){
                Component ERRO = null;
                JOptionPane.showMessageDialog(ERRO, "Preencha todos os campos antes de Cadastrar.");
            }
        }else if(btn_riscoextincao_nao.isSelected()){
            try{
            if(c_raca.getText().trim().equals("") || c_peso.getText().trim().equals("") || c_jaula.getText().trim().equals("")){
                flagCadastro = 1;       // Campos não foram corretamente preenchidos
                throw new CamposInvalidos("avisar");
            }
        }catch(CamposInvalidos e){
            Component ERRO = null;
            JOptionPane.showMessageDialog(ERRO, "Preencha todos os campos antes de Cadastrar.");
        }
        }
            
        //  Se Campos foram preenchidos corretamente e o Animal não está em extinção
        if(flagCadastro == 0 && btn_riscoextincao_nao.isSelected()){
            boolean c = false;

            if (btn_restricao_nao.isSelected()){            // If para pegar o Radio Button para restrição do animal
                c = true;
            }else if (btn_restricao_nao.isSelected()){
                c = false;
            }
            //  Utiliza construtor da classe Animal
            Animal a = new Animal(c_raca.getText(), Float.parseFloat(c_peso.getText()), Short.parseShort(c_jaula.getText()), c);
            list.cadastrarAnimal(a);        // Adiciona na lista de animais
            LoadTableAnimais();     // Carrega na tabela

            //  Caso o animal esteja em Extinção
        }else if(flagCadastro == 0 && btn_riscoextincao_sim.isSelected()){
            boolean c, d;
            c = false;

            if (btn_restricao_nao.isSelected()){            // If para pegar o Radio Button para restrição do animal
                c = true;
            }else if (btn_restricao_nao.isSelected()){
                c = false;
            }

            d = true;   // btn_riscoextincao_sim esta selecionado
            //  Utiliza o construtor da Classe AnimalExtinto
            AnimalExtinto aExt = new AnimalExtinto(c_raca.getText(), Float.parseFloat(c_peso.getText()), Short.parseShort(c_jaula.getText()), c, d, Integer.parseInt(c_especiesrestantes.getText()), Integer.parseInt(c_estimativaextincao.getText()    ));
            list.cadastrarAnimalExt(aExt);      // Adiciona na lista de animais extintos
            LoadTableAnimaisExt();      // Carrega na tabela
        }
        //  Limpa os campos de textos
        c_raca.setText("");
        c_estimativaextincao.setText("");
        c_especiesrestantes.setText("");
        c_jaula.setText("");
        c_peso.setText("");
        //  Desabilita campos de textos
        c_raca.setEditable(false);
        c_peso.setEditable(false);
        c_jaula.setEditable(false);
        c_especiesrestantes.setEditable(false);
        c_estimativaextincao.setEditable(false);

        btn_novo.setEnabled(true);  // Como já foi cadastrado, precisa ser criado um novo cadastro

        // Desbilita botões
        btn_restricao_nao.setEnabled(false);
        btn_restricao_sim.setEnabled(false);
        btn_riscoextincao_nao.setEnabled(false);
        btn_riscoextincao_sim.setEnabled(false);
        btn_cadastrar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        //  Desmarca caixas de seleção dos botões
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

/******************** NOVO****************************/
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

        // Seta os botões e campos após clicar no botão NOVO
        btn_novo.setEnabled(false); // Como foi clicado, não pode ser clicado de novo

        c_raca.setEditable(true);
        c_peso.setEditable(true);
        c_jaula.setEditable(true);
        c_especiesrestantes.setEditable(false);
        c_estimativaextincao.setEditable(false);
        c_buscar.setEditable(true);
        c_buscar2.setEditable(true);

        btn_apagar.setEnabled(true);
        btn_apagar2.setEnabled(true);
        btn_restricao_nao.setEnabled(true);
        btn_restricao_sim.setEnabled(true);
        btn_riscoextincao_nao.setEnabled(true);
        btn_riscoextincao_sim.setEnabled(true);
        btn_cadastrar.setEnabled(true);
        btn_cancelar.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_buscar2.setEnabled(true);
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_riscoextincao_naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riscoextincao_naoActionPerformed
        //  SE animal não estiver em risco de Extinção
        //  desabilita Campos de texto referentes a Extinção
        if(btn_riscoextincao_nao.isSelected()){
            c_especiesrestantes.setEditable(false);
            c_estimativaextincao.setEditable(false);
        }else{      //  CASO CONTRÁRIO habilita Campos de texto referentes a Extinção
            c_especiesrestantes.setEditable(true);
            c_estimativaextincao.setEditable(true);
        }
    }//GEN-LAST:event_btn_riscoextincao_naoActionPerformed

    private void btn_riscoextincao_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_riscoextincao_simActionPerformed
        //  SE animal estiver em risco de Extinção
        //  habilita Campos de texto referentes a Extinção
        if(btn_riscoextincao_sim.isSelected()){
            c_especiesrestantes.setEditable(true);
            c_estimativaextincao.setEditable(true);
        }else{//  CASO CONTRÁRIO desabilita Campos de texto referentes a Extinção
            c_especiesrestantes.setEditable(false);
            c_estimativaextincao.setEditable(false);
        }
    }//GEN-LAST:event_btn_riscoextincao_simActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_apagar2;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar2;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JRadioButton btn_restricao_nao;
    private javax.swing.JRadioButton btn_restricao_sim;
    private javax.swing.JRadioButton btn_riscoextincao_nao;
    private javax.swing.JRadioButton btn_riscoextincao_sim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c_buscar;
    private javax.swing.JTextField c_buscar2;
    private javax.swing.JTextField c_especiesrestantes;
    private javax.swing.JTextField c_estimativaextincao;
    private javax.swing.JTextField c_jaula;
    private javax.swing.JTextField c_peso;
    private javax.swing.JTextField c_raca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_animais;
    private javax.swing.JTable tbl_animaisext;
    // End of variables declaration//GEN-END:variables
}
